{% set name = "tsne" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ./
  # git_url: https://github.com/WiscEvan/tsne.git
  # git_rev: {{ data.get('version') }}

build:
  script: python setup.py build_ext --inplace; python setup.py install

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - distro
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - scipy
    - openblas
    - libcxx
  run:
    - {{ pin_compatible('numpy') }}
    - scipy
    - openblas
    - libcxx

test:
  imports:
    - tsne

about:
  home: {{ data.get('url') }}
  license: APACHE
  license_file: LICENSE
  description: {{ data.get('description') }}
  summary: "Python library containing T-SNE algorithms"
  doc_url: https://pypi.org/project/tsne/
  dev_url: {{ data.get('url') }}

extra:
  maintainers:
   - Evan R. Rees
