{% set name = "tsne" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ./

build:
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - distro
    - pip
    - setuptools
    - cython
    - numpy
    - openblas
    - libcxx
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - openblas
    - libcxx

test:
  imports:
    - tsne
  commands:
    - python -c "from tsne import bh_sne"

about:
  home: https://github.com/danielfrg/py_tsne
  license: APACHE
  license_file: LICENSE
  description: TSNE implementations for python
  summary: "Python library containing T-SNE algorithms"
  doc_url: https://pypi.org/project/tsne/
  dev_url: https://github.com/danielfrg/py_tsne

extra:
  maintainers:
   - Evan R. Rees
